[package]
name = "intellidyn_error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-dynamodb = "0.17.0"
aws-sdk-lambda = "0.17.0"
lambda_http = "0.6.0"