[workspace]
members = [
    "bin/define_company",
    "bin/define_company_code",
    "bin/list_companies",
    "bin/list_company_codes",
    "bin/create_table",
    "lib/db",
    "lib/intellidyn_error",
    "lib/models"
]