[package]
name = "assign_company_code_to_company"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.47.0"
aws-sdk-lambda = "0.17.0"
lambda_http = "0.6.0"
tower-http = { version = "0.3.4", features = ["cors"] }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1.36", features = ["log"] }
tracing-subscriber = { version = "0.3.15", default-features = false, features = ["fmt"] }
serde = { version = "1.0.142", features = ["derive"] }
db = { path = "../../lib/db" }
intellidyn_error = { path = "../../lib/intellidyn_error" }

[[bin]]
name = "assign_company_code_to_company"
path = "src/main.rs"